# Generated by Django 5.0.6 on 2024-05-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='images/recipethumbails/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/recipecontent/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.recipe')),
            ],
        ),
    ]
