# Generated by Django 5.0.6 on 2024-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_mealtype_comment_content_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='mealType',
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealType',
            field=models.ManyToManyField(related_name='recipes', to='content.mealtype'),
        ),
    ]
