# Generated by Django 5.0.6 on 2024-05-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_recipe_mealtype_recipe_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalbum',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipealbum',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images/pictures/'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/familytree/')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_father', to='content.familymember')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_mother', to='content.familymember')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouses', to='content.familymember')),
            ],
        ),
    ]
