# Generated by Django 5.0.6 on 2024-05-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_mediaalbum_private_recipealbum_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='familymember',
            old_name='death_date',
            new_name='deathday',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
