# Generated by Django 5.0.6 on 2024-06-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_mediaalbum_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaalbum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipealbum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
